### ISSUE TITLE
A few questions regarding your setup

### ISSUE THREAD

**Issue by SMerdzhanov** [fabe/gatsby-universal#10]
Hey Fabian,

I don't really experience troubles with your starter and I find it pretty awesome! 🎉 I have a few questions regarding the project and couldn't find a more appropriate place to ask 👍 

#### Questions

❓`/static/social.png` - couldn't find any good usage. On the other hand I see `/src/images/icon.png` which seems to be used globally for the favicon and some other configs. Wouldn't it make more sense to replace `social.png` with `icon.png` or you have other plans?

❓ Regarding the available `npm` scripts I'm a bit confused. I assume the `build` command would be sufficient so we can deploy the generated `/public` folder and its contents? Is this correct assumption? 

❓Can you please elaborate a bit on `/scripts/lighthouse.test.js` and its usage? I find it pretty interesting.

❓Can you please elaborate on the purpose and usage of the `ssr` script?

❓Why do you use your own `site-config.js` file instead of placing its contents directly in `gatsby-config.js`. It can later replace the two usages of `site-config.js`?

#### Feedback

I want to say thank you for this amazing template and I find it one of the best in terms of goals and ideas! There are a few notes I'd like to share as a developer. Feel free to neglect or ignore, but let me know if they make sense and you want to discuss them further.

🤔 The template gets a bit too opinionated making it hard to use out-of-the-box without "clearing" it first. I'd say that most of the code in `/src` can be omitted for simplicity. You can maybe clone this repo so you keep the demo site as is, but then simplify the template itself.

🤔 I'd really love to use this starter as base on top of I want to migrate 2 websites and 1 simple web app. However, given my previous note it would be hard to reuse it directly and most likely will end up "simplifying it" just a bit...

🤔 Consider adding Eslint it gets along with Prettier pretty well.

**Thank you for the amazing work!**

Let me know if my comments do or don't make sense. Cheers!

**Comment by fabe** [comment]
@SMerdzhanov, thanks for the feedback! I'm happy to address your questions.

> ❓/static/social.png - couldn't find any good usage.

This image is used as a fallback for the social images on Twitter cards, Facebook posts, etc. You can find it being referenced inside https://github.com/fabe/gatsby-universal/blob/master/src/components/head/head.js#L58.

> ❓ Regarding the available npm scripts I'm a bit confused. I assume the build command would be sufficient so we can deploy the generated /public folder and its contents? Is this correct assumption?

Yes, `yarn build`/`npm run build` generates the full static site into `/public`. From there you can upload or deploy it anywhere.

> ❓Can you please elaborate a bit on /scripts/lighthouse.test.js and its usage? I find it pretty interesting.

This isn't fully fleshed out, but it runs a [Lighthouse](https://developers.google.com/web/tools/lighthouse/) audit programmatically and checks if all scores are above 90. Right now it uses the previously deployed version, but I'm working on testing the actual build. You can see it in action [inside the CircleCI integration (`yarn test`)](https://circleci.com/gh/fabe/gatsby-universal/52).

> ❓Can you please elaborate on the purpose and usage of the ssr script?

`yarn ssr` runs the build script and serves the `/public` folder on a local server. You can then use this server to run Lighthouse (and other) audits and check how Gatsby builds your site. It's basically a shortcut of doing `gatsby build && gatsby serve`.

> ❓Why do you use your own site-config.js file instead of placing its contents directly in gatsby-config.js.

The only reason so far for this is that I need the same data inside `scripts/favicons.js` to generate the manifest. But you have a point there, I might put everything inside `gatsby-config.js`.

> 🤔 The template gets a bit too opinionated making it hard to use out-of-the-box without "clearing" it first.

True, I think I'll either add some hints (e.g. "first steps") in the readme or a codemod that gets rid of some of the example code.

> it would be hard to reuse it directly and most likely will end up "simplifying it" just a bit...

I would definitely encourage it! This repo is more a collection of patterns, ideas and examples. Cherry picking the things you need and removing the stuff you don't is usually inevitable with any kind of boilerplate.

> 🤔 Consider adding Eslint it gets along with Prettier pretty well.

Gatsby v2 already comes with ESLint set up, so it should be just a matter of adding a `.eslintrc` file into the root of the project. I'll stick with the Gatsby default config for now!

Thanks again! Hope I could clear some stuff up, let me know if there's anything else that comes up.

**Comment by SMerdzhanov** [comment]
Hey!

Thank you for the fast response, didn't expect it although you're actively developing! 

I'm kind of new to Gatsby so this might be the reason for some of the uncertainties. All of your responses seem clear and meaningful to me.

The only remaining question on my end would be about your last point - ESLint.

I haven't encountered any comments about it so far, but will check. If there's truly a reusable configuration that can be used while developing, there's no need to overthink it, right.

Thank you for the help! 🎉 

Cheers!

**Comment by fabe** [comment]
Yep, the ESLint integration is not documented anywhere yet, [there's only a stub](https://next.gatsbyjs.org/docs/eslint/). And I'm just now noticing that you actually need to add a plugin for ESLint to work: mongkuen/gatsby-plugin-eslint.

**Comment by SMerdzhanov** [comment]
Hmm, I don't see the benefits of using the `gatsby-plugin-eslint` vs doing your own 🤔 

I'll search around for this. Thank you for the responses!

Feel free to close this 👍
