### ISSUE TITLE
manifest.json unavailable

### ISSUE THREAD

**Issue by Nichtkunst** [fabe/gatsby-universal#12]
Somehow after the netlify deployment the manifest.json is broken and can't be fetched by the client browser.

site-config.js

`
const path = require('path');

module.exports = {
  siteTitle: `Eiskarussell - Alles dreht sich ums Eis.`,
  siteTitleShort: `Eiskarussell`,
  siteDescription: `Alles dreht sich ums Eis.`,
  siteUrl: `https://www.eiskarussell.at`,
  themeColor: `#FFEB93`,
  backgroundColor: `#FAFAFA`,
  pathPrefix: null,
  logo: path.resolve(__dirname, 'src/images/icon.png'),
  social: {
    twitter: `nichtkunst`,
    fbAppId: ``,
  },
};`

**Comment by fabe** [comment]
Make sure that Netlify is running a build script that includes `yarn build:favicons` (plus `yarn build:dir`), it's the one that should create the manifest and all needed icons.

**Comment by Nichtkunst** [comment]
> Make sure that Netlify is running a build script that includes yarn build:favicons (plus yarn build:dir), it's the one that should create the manifest and all needed icons.

How can I ensure Netlify includes it?

**Comment by fabe** [comment]
It has to be inside the `static` folder *before* the build, or inside the `public` folder *after* the build.

**Comment by Nichtkunst** [comment]
Thanks for the fast reply.
