### ISSUE TITLE
Navigation links scroll to top before transitioning to next page.

### ISSUE THREAD

**Issue by rafaelderolez** [fabe/gatsby-universal#13]
**Steps to reproduce**
1. Scroll down on the homepage of my Gatsby-universal CodeSandbox [example](https://codesandbox.io/s/rz5zy51jq)
2. Click a navigation link

**Expected result**
Page transitions to next page.

**Actual result**
Page scrolls to top before transitioning to the next page.

**Comment by ryanwiemer** [comment]
@rafaelderolez,

In case you haven't already resolved this on your own I encountered a similar issue and a solution was proposed here: 

https://github.com/gatsbyjs/gatsby/issues/5213#issuecomment-428368131

**Comment by rafaelderolez** [comment]
@ryanwiemer I ended up not needing page transitions on the project I used this on but that solution looks promising, thanks!

**Comment by fabe** [comment]
Hey! Thanks for opening this. 

Yes, that seems like a Gatsby-core issue. Closing :)
