### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by steveww** [fabe/gatsby-universal#14]
The install appeared to go OK but when running Gatsby develop

 Error: Cannot find module 'core-js/modules/es6.array.filter'

Any ideas?

**Comment by fabe** [comment]
As a temporary solution you can run `yarn add core-js`. Could you let me know which machine you're on and the installed Gatsby versions (`gatsby info --clipboard`)?

(Duplicate of #9)

**Comment by steveww** [comment]
Looks like core-js is missing from the dependencies. Fixed with nom install --save core-js.
