### ISSUE TITLE
Suggest using mkdirp instead of "mkdir -p" for better cross-platform compatibility

### ISSUE THREAD

**Issue by SeanKilleen** [fabe/gatsby-universal#16]
When running `npm run build` on a Windows system, the build fails on the call to `mkdir -p` because it is not a cross-platform command.

You can resolve this by adding `mkdirp` (an npm package which is x-plat) and changing the call in the build script to `mkdirp /public/icons`. 

(credit to @RyKilleen who walked me through this).

**Comment by fabe** [comment]
@SeanKilleen Thanks for opening this, totally forgot to add that! Fixed in ef7d3c1 🙂

**Comment by SeanKilleen** [comment]
Thanks!
