### ISSUE TITLE
Markdown not displaying as expected

### ISSUE THREAD

**Issue by dderooy** [fabe/gatsby-universal#17]
Styles in 'src/global.css.js' are overriding markdown formatting. Markdown lists and headers etc are displaying as plain text. Is there a way to ignore the global style for all markdown content? 

ps. great template by the way

**Comment by gswirrl** [comment]
Im having a similar issue, but (in my case) the markdown isn't being overridden, it's not being transformed.

Steps to reproduce:

1) `gatsby new my-site https://github.com/fabe/gatsby-universal`
2) in (eg) ~/content/home/intro.md add

```
# Broken :-(

[link](https://www.google.com)
```

3) Expected: 

```
<h1>Broken :-(</h1>
<a href="https://www.google.com">link</a>
```

<img width="690" alt="screenshot 2018-12-19 at 17 08 52" src="https://user-images.githubusercontent.com/17145418/50235861-ceca4280-03b0-11e9-841a-cc3e1cddaf0e.png">

**Comment by gswirrl** [comment]
@fabe thanks so much for the full reply - id just figured it out and was editing my comment! :-) once again, thank you - love the starter!

**Comment by dderooy** [comment]
@fabe Thank you for the help. I have it displaying properly now 😄 👍

**Comment by fabe** [comment]
@gswirrl @dderooy Thanks, let me know if anything else comes up! 🙂

**Comment by dannycahyo** [comment]
I have the same issues. I've already used HTML to display my markdown file. For example like this : 
 `<div dangerouslySetInnerHTML={{ __html: html }}  />`
 I still can't display the markdown file properly, here is the case. I want to display ## Heading 2, but it just shows Heading 2, which is just plain text.
 Besides, I also use Chakra UI. 
 
 Can anyone give me the solution, please?
