### ISSUE TITLE
Icons not found

### ISSUE THREAD

**Issue by gswirrl** [fabe/gatsby-universal#18]
With a new project,

```
 gatsby new my-site https://github.com/fabe/gatsby-universal
```

I do `gatsby build` and `gatsby serve` 

the html that is generated references eg `icons/apple-touch-icon-57x57.png` etc... but those files don't seem to exist. I can't find a subfolder `icons` in `public` at all.  What am I doing wrong?

**Comment by gswirrl** [comment]
Ignore me, im an idiot

```
node scripts/favicons
```

**Comment by fabe** [comment]
Hey! Yep, it's better to use the npm scripts (e.g. `yarn build`/`npm run build`) instead of directly using the `gatsby-cli`. Check out the [usage section](https://github.com/fabe/gatsby-universal#usage) in the readme and let me know if you have any other questions 👍
