### ISSUE TITLE
Back button broken

### ISSUE THREAD

**Issue by scottarnold** [fabe/gatsby-universal#3]
This is a great!

I noticed the browser's back button was broken. Any idea what's causing that?

Steps to reproduce:
1. Open [https://gatsby-universal.netlify.com/](https://gatsby-universal.netlify.com/)
2. Click 'About'
3. Use mouse or browser back button

**Comment by fabe** [comment]
Thanks for opening this! Happened because of a relict inside `gatsby-browser`, fixed in 136a452 😊
