### ISSUE TITLE
totally newbie question

### ISSUE THREAD

**Issue by ahmetcetin** [fabe/gatsby-universal#41]
thx a lot for putting together a nice template, planning to use it for a simple web app that i'm doing as side project. although i use react on a daily basis, i've used graphql on toy projects only and i'm a newbie on gatsby. So please forgive me if what i'm asking looks like a dumb question :)

just tried to create a new page called test, created test.js in pages folder:

```
import React from 'react';
import PropTypes from 'prop-types';
import { graphql } from 'gatsby';
import Layout from 'components/layout';
import Box from 'components/box';
import Head from 'components/head';

const Test = ({ data }) => (
  <Layout>
    <Head pageTitle={data.testJson.title} />
    <Box>
      <div
        dangerouslySetInnerHTML={{
          __html: data.testJson.content.childMarkdownRemark.html,
        }}
      />
    </Box>
  </Layout>
);

Test.propTypes = {
  data: PropTypes.object.isRequired,
};

export default Test;

export const query = graphql`
  query TestQuery {
    testJson {
      title
      content {
        childMarkdownRemark {
          html
        }
      }
    }
  }
`;
```

Just copy of about page, renamed all about things to test.

created test folder with test.json and content.md under /content folder, just copy of about (markdown file is just a line of text though).

I got the following error when I save the project:
```
Unknown field 'testJson' on type 'Query'. Source: document `TestQuery` file: `GraphQL request`
```

Obviously it's related with this part it looks:
```
export const query = graphql`
  query TestQuery {
    testJson {
      title
      content {
        childMarkdownRemark {
          html
        }
      }
    }
  }
`;
```

As I remember from the gatsby tutorial in gatsby's website, the queries are created using gatsby-node.js file, but it looks it's just a boilerplate in this template. Just trying to understand where aboutJson query is defined, so I can define testJson accordingly but no joy so far. Can you please explain, how can I add a new page using this template?

Cheers,

**Comment by ahmetcetin** [comment]
well, nevermind, i just stopped and rerun gatsby develop, now it works, just to understand, do we need to restart for every page we add?

**Comment by fabe** [comment]
Hey @ahmetcetin! Generally when adding new pages in Gatsby, there's no need to restart the dev server. However, new GraphQL queries are not created on-the-fly as far as I know, and are only initialized once the server starts or a build is made. So if you're depending on a new GraphQL query, just quickly restart the server :)
