### ISSUE TITLE
[V2] Modal not opening in Firefox

### ISSUE THREAD

**Issue by Legym** [fabe/gatsby-universal#5]
I just wanted to let you know that the when you open the modal in Firefox devtools it throws an error and the page turns white. 

The error in the console shows up as
`this.modal.showModal is not a function`

This repo has been a lifesaver. Thank you!

**Comment by fabe** [comment]
Thanks! I'm using `<dialog>`, which is currently [only supported in Chrome](https://caniuse.com/#feat=dialog). Kinda related to #2, I might be adding a working polyfill soon, or just use `<div>`s instead!
