### ISSUE TITLE
Cannot find module 'core-js/modules/es6.array.filter'

### ISSUE THREAD

**Issue by cutemachine** [fabe/gatsby-universal#9]
I get an error on a clean installation.

`Error: Cannot find module 'core-js/modules/es6.array.filter'`

I'm using Gatsby 2.0.0-rc.1

Adding core-js as a dependency resolves the issue (`npm add core-js --save`), but I'm not sure this is the correct solution to the problem.

PS: Thanks for the great starter.

**Comment by fabe** [comment]
Hey, I can't reproduce this on a clean install on my machine, so this might be an isolated issue. I'll keep this open in case anybody else runs into this.

**Comment by enrichit** [comment]
Same deal for me.

  Cannot find module 'core-js/modules/es6.regexp.to-string'

Adding the missing core-js fixed it as reported.

**Comment by fabe** [comment]
Not sure what's wrong here, but I added `core-js` to the `devDependencies`, so this should hopefully fix it. Thanks!
